apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-api
  namespace: quote-api
  annotations:
    argocd-image-updater.argoproj.io/image-list: quoteapiacr123.azurecr.io/quote-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quote-api
  template:
    metadata:
      labels:
        app: quote-api
    spec:
      containers:
      - name: quote-api
        image: quoteapiacr123.azurecr.io/quoteapi:latest #Replace wih your ACR name
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector:4318/v1/traces"

---
apiVersion: v1
kind: Service
metadata:
  name: quote-api
  namespace: quote-api
spec:
  type: NodePort
  selector:
    app: quote-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080